### ISSUE TITLE
Dynamic lib not loading

### ISSUE THREAD

**Issue by lxkant** [Estimote/iOS-Bluetooth-Scanning#1]
>dyld: Library not loaded: @rpath/EstimoteBluetoothScanning.framework/EstimoteBluetoothScanning
  Referenced from: /var/containers/Bundle/Application/4698D150-D8DA-44F3-BDF7-8ED089AB424B/EstimoteAsset.app/EstimoteAsset
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/4698D150-D8DA-44F3-BDF7-8ED089AB424B/EstimoteAsset.app/Frameworks/EstimoteBluetoothScanning.framework/EstimoteBluetoothScanning: code signing blocked mmap() of '/private/var/containers/Bundle/Application/4698D150-D8DA-44F3-BDF7-8ED089AB424B/EstimoteAsset.app/Frameworks/EstimoteBluetoothScanning.framework/EstimoteBluetoothScanning'
Message from debugger: Terminated due to signal 6

**Comment by chwastek** [comment]
Hey @lxkant 
sorry for such delay - is it still a problem? If so, did you add EstimoteBluetoothScanning as _embedded_ framework to your project + set up properly frameworks search paths in Build Settings?
