### ISSUE TITLE
EBSUniversalScannerDelegate methods do not get called 

### ISSUE THREAD

**Issue by AmjadKhalil96** [Estimote/iOS-Bluetooth-Scanning#2]
none of the EBSUniversalScannerDelegate methods gets called although i implemented the EBSUniversalScannerDelegate
i passed an empty array of the devices i want to scan because i want to scan all Estimote devices

**Comment by chwastek** [comment]
Hey @AmjadKhalil96 
That is actually a quite interesting case 😄 I guess we never planned to scan for everything. In the meantime just provide an array of stuff you want to scan for.

Why exactly you need to scan for every possible (within provided by EstimoteBluetoothScanning) packet? And equally important what exactly you wanted to scan for, what kind of devices?

**Comment by AmjadKhalil96** [comment]
it worked, i was passing an empty array of what i want to scan.
when i passed an array of general devices it worked :D 
thanks

**Comment by chwastek** [comment]
Happy to help 😄
